#!/bin/bash
# Creates an index.ts with exports of all .ts files in that directory

set -ex

if [ -f index.ts ]; then
  echo "previous index.ts found, removing..."
  rm index.ts 2> /dev/null
fi

shopt -s nullglob

for file in *.{tsx,ts};
do
    [[ $file =~ \.test\.tsx?$ ]] && continue

    BASE="${file%.*}"
    echo "export * from './$BASE';" >> index.ts
done

